[package]
name = "is-url"
version = "1.0.2"
author = "Mauro Baladés"
description = "A rust library to check if a string is an URL."
edition = "2018"
license = "MIT"
readme="README.md"
repository = "https://github.com/mauro-balades/is-url"

[dependencies]
regex = "1"
